// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCivI_yI3JvE38GWFaUbgLxCY4CtuisSB4',
    appId: '1:251114790454:web:0d5fbe8d4edcb7362a4297',
    messagingSenderId: '251114790454',
    projectId: 'devi-jewels',
    authDomain: 'devi-jewels.firebaseapp.com',
    storageBucket: 'devi-jewels.firebasestorage.app',
    measurementId: 'G-J3909HYJ0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgwde_BU3i5sq29anfGrn6zk6m6sfKE4g',
    appId: '1:251114790454:android:19ea2f05447e19432a4297',
    messagingSenderId: '251114790454',
    projectId: 'devi-jewels',
    storageBucket: 'devi-jewels.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXlEUx1D4fnmm5kj6U2urao4UBHJOrnI',
    appId: '1:251114790454:ios:7425f886534f97882a4297',
    messagingSenderId: '251114790454',
    projectId: 'devi-jewels',
    storageBucket: 'devi-jewels.firebasestorage.app',
    iosBundleId: 'com.example.jewelAdmin',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMXlEUx1D4fnmm5kj6U2urao4UBHJOrnI',
    appId: '1:251114790454:ios:7425f886534f97882a4297',
    messagingSenderId: '251114790454',
    projectId: 'devi-jewels',
    storageBucket: 'devi-jewels.firebasestorage.app',
    iosBundleId: 'com.example.jewelAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCivI_yI3JvE38GWFaUbgLxCY4CtuisSB4',
    appId: '1:251114790454:web:9d4bd5a42a663e302a4297',
    messagingSenderId: '251114790454',
    projectId: 'devi-jewels',
    authDomain: 'devi-jewels.firebaseapp.com',
    storageBucket: 'devi-jewels.firebasestorage.app',
    measurementId: 'G-3NMEXQNV4S',
  );
}
